name: CD - Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to production
        run: |
          az container create \
            --resource-group sit722-rg \
            --name sit722-prod-app \
            --image sukriti722acr.azurecr.io/sit722app:${{ github.sha }} \
            --registry-login-server sukriti722acr.azurecr.io \
            --cpu 1 --memory 1.5 \
            --dns-name-label sit722-prod \
            --ports 80
